### your site title here

title: Jeneta Nwosu
description: Economics | Vanderbilt | Real.

baseurl: "" #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: # no thanks to spam

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: "https://twitter.com/JenetaNwosu"
linkedin: "https://www.linkedin.com/in/jeneta-nwosu-76300426b/"
github: "https://github.com/jadannanwosu/"
bluesky: "https://bsky.app/profile/jadannanwosu.bsky.social"



# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
